name: 'test shibui'
description: 'Provide a description here'
author: 'test shibui org'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: '10'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'message-square'
  color: 'orange'
  