name: 'test composite'
description: 'Provide a description here'
author: 'test shibui org'
inputs:
  test:
    required: true
    description: 'input description here'
    default: 'aaabbb'
runs:
  using: "composite"
  steps:
    - id: first
      run: echo ${{ inputs.test }}
      shell: bash
    - id: second
      run: ./composite_action/run.sh
      shell: bash
      env:
        INPUT: ${{ inputs.test }}
    - name: third
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - id: fourth
      run: pip install numpy
      shell: bash
