name: 'test python docker'
description: 'Provide a description here'
author: 'test shibui org'
inputs:
  test:
    required: true
    description: 'input description here'
    default: 'aaabbb'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--test'
    - ${{ inputs.test }}
branding:
  icon: 'message-square'
  color: 'orange'
